Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose
you have collected data on the amount of time students spend studying for an exam and their final exam
scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

In [1]:
time_spent_studying = [10, 15, 20, 25, 30]
final_exam_scores = [60, 70, 80, 90, 95]

In [2]:
import numpy as np

In [3]:
np.corrcoef(time_spent_studying,final_exam_scores)

array([[1.        , 0.99388373],
       [0.99388373, 1.        ]])

Interpretation:

If the Pearson correlation coefficient is close to 1, it indicates a strong positive linear relationship. In the context of the example, it would suggest that as the time spent studying increases, final exam scores tend to increase.
If the coefficient is close to -1, it indicates a strong negative linear relationship. In this case, it would suggest that as the time spent studying increases, final exam scores tend to decrease.
If the coefficient is close to 0, it indicates a weak or no linear relationship between the two variables.

Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables.
Suppose you have collected data on the amount of sleep individuals get each night and their overall job
satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two
variables and interpret the result.

In [5]:
job_satisfaction=np.random.randint(1,11,10)
job_satisfaction

array([ 5, 10,  9,  1,  8,  5,  1,  5,  7,  4])

In [6]:
sleep_data=np.random.randint(1,11,10)
sleep_data

array([ 9,  5,  9,  8,  3,  2, 10,  1,  3,  1])

In [7]:
from scipy.stats import spearmanr

In [12]:
spearmanr(sleep_data,job_satisfaction)[0]

-0.043479099562495904

Q3. Suppose you are conducting a study to examine the relationship between the number of hours of
exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables
for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation
between these two variables and compare the results.

In [13]:
exercise=np.random.randint(1,11,50)
exercise

array([ 9,  5,  7,  1,  3,  9,  2,  2, 10,  2,  9,  5,  5,  2,  9,  8,  3,
        6,  8,  2,  9,  4,  4,  3,  6,  8,  9, 10,  7,  7,  9,  3,  1,  8,
        8,  8,  3, 10,  4,  9,  3,  2,  5,  4,  1,  9,  3,  2,  1,  4])

In [16]:
bmi=np.random.uniform(18.5,24.9,50)
bmi

array([23.11422233, 19.72967184, 21.10469114, 23.7592216 , 19.90940891,
       23.52480254, 24.06753965, 22.62610305, 23.85984273, 21.76742146,
       20.39083958, 21.27382161, 20.82398377, 21.96765745, 24.05725655,
       20.12549546, 20.09474673, 20.80909914, 22.37301306, 23.39330881,
       20.90024537, 21.02963944, 21.33519434, 21.2545728 , 22.74426976,
       24.81339663, 22.95308257, 22.60440022, 20.89709666, 24.13450304,
       23.77360501, 20.55254638, 22.42815438, 23.78139729, 21.87747106,
       22.76103209, 21.62448518, 22.98622563, 24.61110135, 23.78444688,
       19.614994  , 19.58751188, 23.72778204, 20.97385567, 19.30875262,
       21.64937742, 23.16663454, 19.32233924, 22.31684682, 23.62449636])

In [19]:
np.corrcoef(exercise,bmi)

array([[1.        , 0.30928039],
       [0.30928039, 1.        ]])

In [18]:
spearmanr(exercise,bmi)[0]

0.29598774697730706

Q4. A researcher is interested in examining the relationship between the number of hours individuals
spend watching television per day and their level of physical activity. The researcher collected data on
both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between
these two variables.

In [20]:
tv=np.random.uniform(1,11,50)
tv

array([ 9.81839659,  1.32055232,  2.96094687,  8.42149484,  3.1530179 ,
        1.79647643,  5.47618307,  2.89127235,  5.73323911, 10.21626243,
       10.92418684,  3.23580779, 10.88691281,  6.51467335,  8.26896789,
        1.67861001,  7.41695073,  2.33400543,  5.16013704,  5.70438718,
        6.47824463,  7.91092097,  1.04620854,  2.80352682,  8.0315888 ,
       10.50150766,  7.41650374,  4.61455007,  3.22205043,  1.89722232,
        1.26565014,  3.27023378,  8.91616596,  7.52746633,  4.10916394,
        6.48845592,  4.21548928,  3.64970017,  8.58843592,  8.45817153,
        4.49000974,  4.76241948,  6.17842495,  3.84686415,  7.19561336,
        4.38708505,  6.14360622,  3.62504091,  9.41166445,  9.19176667])

In [21]:
physicalact=np.random.uniform(1,11,50)
physicalact

array([ 4.7450082 ,  6.99039265,  4.02158029,  4.58156462,  1.37368352,
        9.46450751,  7.0860169 ,  3.44561755,  3.08855075,  5.99074347,
        7.3801214 ,  3.25173672,  9.50535752,  9.05709539,  4.59680502,
       10.92091399,  4.79205252,  7.80760192,  5.72462386,  3.13144515,
        6.38044661,  8.92832958,  8.55132253,  1.49048834,  9.16111822,
        8.08633099,  8.86946913,  4.97102146,  6.96319049,  2.68146708,
        3.97399703,  8.70127721,  9.62618145,  2.20305884,  6.98496386,
        4.3110614 ,  6.98218955,  7.0063454 ,  1.83566576,  6.65843474,
        2.9749866 ,  6.95149736,  7.96513961,  5.15745436, 10.20425205,
       10.26338943,  6.54658767,  7.77791289,  1.4362873 ,  4.77201677])

In [ ]:
np.corrcoef(tv,physicalact)

array([[1.        , 0.03819087],
       [0.03819087, 1.        ]])

Q6. A company is interested in examining the relationship between the number of sales calls made per day
and the number of sales made per week. The company collected data on both variables from a sample of
30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.

In [33]:
salesperday=np.random.randint(10,100,30)
salesperday

array([34, 94, 66, 88, 98, 64, 23, 15, 59, 30, 72, 31, 59, 10, 68, 37, 72,
       16, 87, 48, 87, 79, 59, 18, 75, 55, 54, 40, 34, 54])

In [34]:
salesperweek=np.random.randint(100,1000,30)
salesperweek

array([823, 438, 685, 310, 171, 384, 171, 623, 283, 467, 185, 991, 110,
       549, 434, 466, 688, 118, 776, 920, 708, 487, 998, 803, 618, 339,
       274, 138, 706, 798])

In [35]:
from scipy.stats import pearsonr

In [37]:
pearsonr(salesperday,salesperweek)[0]

-0.09683074597890218

In [38]:
np.corrcoef(salesperday,salesperweek)

array([[ 1.        , -0.09683075],
       [-0.09683075,  1.        ]])